version: '2.0.2'

services:

  db:
    image: postgres:13.4
    container_name: vw-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command: postgres -c listen_addresses=*
    ports:
        - '3306:5432'

  api:
    image: 'vwapi/oreo:${API_VERSION}'
    container_name: vw-api
    depends_on: 
        - db
    environment:
      DB_URL: host.docker.internal:3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      API_PORT: ${API_PORT}
      API_VALIDATION_ENABLED: ${API_VALIDATION_ENABLED}
      API_SECURITY_ACCESS_TOKEN_LIFETIME: ${API_SECURITY_ACCESS_TOKEN_LIFETIME}
      API_SECURITY_REFRESH_TOKEN_LIFETIME: ${API_SECURITY_REFRESH_TOKEN_LIFETIME}
    ports:
        - '${API_PORT:-8080}:8080'
