version: '2.0.2'

services:

  db:
    image: postgres:13.4
    container_name: vw-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command: postgres -c listen_addresses=*
    ports:
      - '3306:5432'

  api:
    image: 'vwapi/oreo:${API_VERSION}'
    container_name: vw-api
    environment:
      DB_URL: host.docker.internal:3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - '8080:8080'
